version: '3.3'
services:
  nginx:
   container_name: nginx
   image: nginx
   restart: always
   depends_on:
      - jetty
   ports:
      - 80:80
      - 443:443
   volumes:
      - ./nginx:/etc/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
   networks:
   - front

  jetty:
   container_name: jetty
   image: jetty:9.4.11
   restart: always
   depends_on:
       - mysql
   volumes:
       - ./web/target:/var/lib/jetty/webapps
       - ./logs/jetty:/logs/jetty
   environment:
       - "JAVA_OPTIONS=-Xmx1g -Xms1g -Djetty.logs=/logs/jetty -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:MaxGCPauseMillis=400 -XX:GCPauseIntervalMillis=8000 -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime -Xloggc:gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=4 -XX:GCLogFileSize=10240K"
   networks:
   - front
   - back

  mysql:
   container_name: mysql
   image: mysql/mysql-server
   command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
   environment:
    MYSQL_DATABASE: xinran
    MYSQL_ROOT_PASSWORD: kidding
    MYSQL_USER: kidding
    MYSQL_PASSWORD: kidding
   ports:
   - "3306:3306"
   volumes:
   - /home/admin/data/mysql:/var/lib/mysql

   restart: always
   networks:
   - back

networks:
  front:
  back: